OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "s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"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"